import Head from 'next/head'
import Image from 'next/image'
import Column from '../components/Grid/Column'
import Container from '../components/Grid/Container'
import Row from '../components/Grid/Row'
import Header from '../components/Header'
import HeroSection from '../components/HeroSection'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container type='fluid'>
        <Row gutter={16}>
          
          <Column sm={8} md={4} lg={8} xl={4} xxl={12}>
            <Header />
          </Column>
          
          <Column sm={8} md={4} lg={8} xl={4} xxl={9}>
            
          </Column>
          
          <Column sm={8} md={4} lg={8} xl={4} xxl={3}>
            b
          </Column>

        </Row>
      </Container>

      {/* <footer className={styles.footer}>
        
      </footer> */}
    </div>
  )
}
