import Head from 'next/head'
import Image from 'next/image'
import { Column, Container, Row } from '../components/Grid/styles'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <Row>
          <Column sm={4} md={12} lg={6}>sm 6 / md 12 / lg 6</Column>
          <Column sm={4} md={6} lg={6}>sm 6 / md 6 / lg 6</Column>
          <Column sm={4} md={6} lg={12}>sm 12 / md 6 / lg 12</Column>
        </Row>
      </Container>

      {/* <footer className={styles.footer}>
        
      </footer> */}
    </div>
  )
}
